export const USE_LIVE_GOOGLE_MAPS = process.env.USE_LIVE_GOOGLE_MAPS === 'true' && Boolean(process.env.GOOGLE_MAPS_API_KEY)
export const GROUPING_TIME_TOLERANCE_MINUTES = 15
export const GROUPING_DIRECTION_TOLERANCE_DEGREES = 55
export const GROUPING_ROUTE_PADDING_KM = 4
